### ISSUE TITLE
panel dock fill 

### ISSUE THREAD

**Issue by JiYongfei** [muxiang/PowerLib#1]
![image](https://github.com/muxiang/PowerLib/assets/28884689/39d024a3-3150-4f8e-bfdb-63d909e68c4d)

添加一个Panel控件然后填充后，底部会出现一个标题等高度的区域始终填充不到，，，，，大佬能解决下吗

**Comment by muxiang** [comment]
你好，我在Win10 x64与VS2022中未能重现出此问题，你的OS和VS版本是什么？窗口设计器中窗口的FormBorderStyle是什么？最好能提供一下Designer.cs源码，我这边尝试重现一下

**Comment by JiYongfei** [comment]
你好，大佬，我的Win11专业版本，vs2022，用的0.9 的版本，，，，
[PowerLib-0.9.zip](https://github.com/muxiang/PowerLib/files/15270777/PowerLib-0.9.zip)
代码我添加到附件，您试试看。。。

**Comment by muxiang** [comment]
哦，你用的是release，我只更新了代码，没有及时更新release，稍后会更新，不好意思

**Comment by JiYongfei** [comment]
感谢，感谢。。。。。O(∩_∩)O

**Comment by muxiang** [comment]
已上传最新版本Release：[https://github.com/muxiang/PowerLib/releases/tag/v1.0.0.12](url)
如果使用nuget，可以在VS的nuget管理器中快速安装，并方便后续一键获取新版本：NuGet\Install-Package PowerLib.Winform -Version 1.0.12
