### ISSUE TITLE
双击标题栏后再双击恢复默认大小后，

### ISSUE THREAD

**Issue by JiYongfei** [muxiang/PowerLib#2]
![image](https://github.com/muxiang/PowerLib/assets/28884689/f181fa56-b132-48e4-8ee7-da98c1c07444)
双击标题栏后再次双击标题栏恢复默认大小
会发现默认的大小改变了。。。。重复几次后就这样了。。
![image](https://github.com/muxiang/PowerLib/assets/28884689/650241dd-ce5b-458f-a5be-5f720c83148e)

**Comment by muxiang** [comment]
感谢关注，该bug已在commit 32630da中修复，请更新后验证
