### ISSUE TITLE
最大化后全屏幕显示了，看不到任务栏

### ISSUE THREAD

**Issue by JiYongfei** [muxiang/PowerLib#3]
![image](https://github.com/muxiang/PowerLib/assets/28884689/cb82b01b-6725-4222-bc77-e14d9f38629f)
你好，最大化显示后，看不到任务栏了，全屏显示，设计就是这样，是吗？

**Comment by muxiang** [comment]
是bug，目前正在着手解决

**Comment by muxiang** [comment]
已在版本v1.0.0.13中修复[https://github.com/muxiang/PowerLib/releases/tag/v1.0.0.13](url)
